[package]
name = "divine-office"
version = "0.1.0"
edition = "2021"

[dependencies]

rouille = "3.6"
chrono = "0.4"
computus = { version = "1.1", features = ["chrono"] }
regex = "1"
lazy_static = "1.4"